### ISSUE TITLE
New bans don't show up anymore

### ISSUE THREAD

**Issue by JohnFulpWillard** [bobbahbrown/CentCom#52]
Latest bans don't seem to show up for TG/Fulp, Fulp stopped working since https://github.com/fulpstation/fulpstation/pull/846 was merged (one of the PRs which they update to latest TG code)

Example: https://tgstation13.org/phpBB/viewtopic.php?f=34&t=32749&p=656628
https://centcom.melonmesa.com/viewer/view/fizziz

TG permabans are public, but this one hasn't showed up

Fulp's ban API: https://api.fulp.gg/bans/50/1
The 3 most latest banned from the time of reporting:
https://centcom.melonmesa.com/viewer/search/floatingbudgie
https://centcom.melonmesa.com/viewer/view/hbreddl10
https://centcom.melonmesa.com/viewer/view/funnytoilet

None of these bans show up in the database, fulp's bans are all meant to be public (compared to tg's perma-only, this one is a much better example).

**Comment by bobbah** [comment]
crawler appears to have silently failed recently, restarted and it appears to be fine, resolved. thanks for the report.

for the future i'll look at improving/implementing some form of healthchecks so this is less likely to occur in the future.

**Comment by bobbah** [comment]
also just to clarify that fizz person's ban wouldn't appear currently as it is a permaban that was reduced hence no longer perma.

centcom directly mirrors bans so it actually removes bans from the db that no longer appear at the source.

**Comment by JohnFulpWillard** [comment]
> centcom directly mirrors bans so it actually removes bans from the db that no longer appear at the source.

This hasn't been the case for my fulp bans, i dunno if its unique to fulp though

**Comment by bobbah** [comment]
> > centcom directly mirrors bans so it actually removes bans from the db that no longer appear at the source.
> 
> This hasn't been the case for my fulp bans, i dunno if its unique to fulp though

Assuming your ckey is johnwillard then you do still appear in the fulp API; the application is functioning as intended.

https://api.fulp.gg/bans/50/90

![image](https://user-images.githubusercontent.com/10467687/225479105-c28d8fff-b57d-4093-9168-4fe3cadfdc90.png)
